## Global application config
application:
  id: paradise
  name: userpreference


## AWS
cloud.aws:
  # amount of time to wait (in milliseconds) when initially establishing a request connection before giving up and timing out. A value of 0 means infinity, and is not recommended.
  connection.timeout: 5000
  # maximum number of allowed open HTTP connections
  connection.max: 500
  # amount of time to wait (in milliseconds) for data to be transfered over an established, open connection before the connection times out and is closed. A value of 0 means infinity, and isn't recommended.
  socket.timeout: 5000
  credentials.accessKey: Replace_it_with_AWS_accessKey
  credentials.secretKey: Replace_it_with_AWS_secretKey
  region.static: ap-southeast-2

## AWS DynamoDB
dynamo:
  endpoint: "http://localhost:8000"

## Apache ActiveMQ
spring.jms.pub-sub-domain: true
## External ActiveMQ settings
#spring.activemq.broker-url: tcp://localhost:61616
#spring.activemq.user: admin
#spring.activemq.password: admin